apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lsevr4z82-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:03a1e582498ee3698d93384ee93f8122f9381ae8@sha256:2829fc603e2ca115ef1894c64ab966b14d87d7c4f29be413f2b5c727ab6e8939
          name: container-image
