apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lsevr4z82-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lsevr4z82-java-springboot-gitops